from __future__ import annotations

from backend.app.graph.state import GraphState
from backend.app.llm import run_reviewer_agent, run_writer_agent
from backend.app.pipeline.confidence_scorer import score_confidence
from backend.app.pipeline.evidence_extractor import extract_evidence
from backend.app.pipeline.final_report_generator import generate_final_reports
from backend.app.pipeline.report_reviewer import review_report
from backend.app.pipeline.report_writer import write_report
from backend.app.pipeline.rule_validator import validate_rules
from backend.app.pipeline.transcript_processor import process_transcripts


def transcript_node(state: GraphState) -> GraphState:
    state.lesson = process_transcripts(state.lesson)
    state.add_event(
        "transcript_processor",
        "Transcript segments normalized and ASR metadata preserved.",
        status="passed",
        metadata={
            "teacher_segments": len(state.lesson.transcripts.teacher),
            "student_segments": len(state.lesson.transcripts.student),
        },
    )
    return state


def evidence_node(state: GraphState) -> GraphState:
    if not state.include_pronunciation:
        state.lesson.pronunciation_assessments = []
    state.lesson = extract_evidence(state.lesson)
    state.add_event(
        "evidence_extractor",
        "Evidence extracted from transcripts and pronunciation assessments.",
        status=(
            "passed"
            if state.lesson.evidence.knowledge_points
            and state.lesson.evidence.teacher_questions
            and state.lesson.evidence.student_questions
            and state.lesson.evidence.corrections
            and state.lesson.evidence.homework
            and state.lesson.evidence.pronunciation
            else "warning"
        ),
        metadata={
            "knowledge_points": len(state.lesson.evidence.knowledge_points),
            "teacher_questions": len(state.lesson.evidence.teacher_questions),
            "student_questions": len(state.lesson.evidence.student_questions),
            "corrections": len(state.lesson.evidence.corrections),
            "homework": len(state.lesson.evidence.homework),
            "pronunciation": len(state.lesson.evidence.pronunciation),
        },
    )
    return state


def writer_node(state: GraphState) -> GraphState:
    agent_result = run_writer_agent(
        state.lesson,
        requested_mode=state.requested_agent_mode,
        config=state.llm_config,
        revision_instruction=state.revision_instruction,
    )
    state.record_llm_trace(agent_result.trace)
    if agent_result.mode == "real_llm" and agent_result.output is not None:
        state.lesson.draft_report = agent_result.output
    else:
        state.lesson = write_report(state.lesson)
    if state.revision_instruction:
        state.lesson.teacher_edit_log.append(
            {
                "event": "writer_revision_applied",
                "revision_count": state.revision_count,
                "revision_instruction": state.revision_instruction,
            }
        )
    state.add_event(
        "writer_agent",
        "Draft report generated by Writer Agent.",
        status="passed" if agent_result.mode == "real_llm" and not state.revision_instruction else "warning",
        metadata={
            **agent_result.trace,
            "revision_instruction": state.revision_instruction,
            "homework_items": len(state.lesson.draft_report.homework_items),
            "pronunciation_feedback": len(state.lesson.draft_report.pronunciation_feedback),
        },
    )
    return state


def confidence_node(state: GraphState) -> GraphState:
    state.lesson = score_confidence(state.lesson)
    state.add_event(
        "confidence_scorer",
        "Module-level confidence scores and risk highlights generated.",
        status=(
            "warning"
            if any(value in {"medium", "low"} for value in state.lesson.confidence_scores.values())
            else "passed"
        ),
        metadata={
            "confidence_scores": dict(state.lesson.confidence_scores),
            "risk_count": len(state.lesson.risk_highlights),
        },
    )
    return state


def rule_validator_node(state: GraphState) -> GraphState:
    state.lesson = validate_rules(state.lesson, revision_count=state.revision_count)
    state.add_event(
        "rule_validator",
        "Hard rules evaluated before reviewer.",
        status=(
            "failed"
            if state.lesson.rule_validation_result.blocking_issues
            else "warning"
            if state.lesson.rule_validation_result.warnings
            else "passed"
        ),
        metadata={
            "pass": state.lesson.rule_validation_result.pass_,
            "blocking_issues": list(state.lesson.rule_validation_result.blocking_issues),
            "warnings": list(state.lesson.rule_validation_result.warnings),
        },
    )
    return state


def reviewer_node(state: GraphState) -> GraphState:
    agent_result = run_reviewer_agent(
        state.lesson,
        requested_mode=state.requested_agent_mode,
        config=state.llm_config,
        revision_count=state.revision_count,
    )
    state.record_llm_trace(agent_result.trace)
    if agent_result.mode == "real_llm" and agent_result.output is not None:
        state.lesson.review_result = agent_result.output
    else:
        state.lesson = review_report(state.lesson, revision_count=state.revision_count)
    state.revision_instruction = state.lesson.review_result.revision_instruction
    state.add_event(
        "reviewer_agent",
        "Draft report reviewed by Reviewer Agent.",
        status="passed" if state.lesson.review_result.pass_ else "failed",
        metadata={
            **agent_result.trace,
            "pass": state.lesson.review_result.pass_,
            "score": state.lesson.review_result.score,
            "issues": list(state.lesson.review_result.issues),
            "revision_instruction": state.lesson.review_result.revision_instruction,
        },
    )
    return state


def route_after_review(state: GraphState) -> GraphState:
    if state.lesson.rule_validation_result.pass_ and state.lesson.review_result.pass_:
        state.add_event(
            "conditional_edge",
            "Review passed; route to teacher review gate.",
            route="teacher_review_gate",
            status="passed",
        )
        return state

    if state.revision_count < state.max_revisions:
        state.revision_count += 1
        state.add_event(
            "conditional_edge",
            "Review failed; route back to Writer node for revision.",
            route="writer_revision",
            status="warning",
            metadata={"next_revision_count": state.revision_count},
        )
        return state

    state.stopped_reason = "max_revision_loop_reached"
    state.add_event(
        "conditional_edge",
        "Review failed and revision loop limit reached; route to manual teacher review.",
        route="manual_review",
        status="failed",
    )
    return state


def teacher_review_gate_node(state: GraphState) -> GraphState:
    if state.lesson.teacher_review.status == "confirmed":
        state.add_event(
            "teacher_review_gate",
            "Teacher review is confirmed; final report generation is allowed.",
            route="final_report",
            status="passed",
            metadata={"teacher_review_status": state.lesson.teacher_review.status},
        )
    else:
        state.add_event(
            "teacher_review_gate",
            "Teacher review is pending; outputs remain draft/pending.",
            route="end",
            status="pending",
            metadata={"teacher_review_status": state.lesson.teacher_review.status},
        )
    return state


def final_report_node(state: GraphState, audiences: list[str] | None = None) -> GraphState:
    state.lesson = generate_final_reports(state.lesson, audiences=audiences)
    state.add_event(
        "final_report_generator",
        "Final report generator ran with teacher-review-aware status.",
        route="end",
        status="passed" if state.lesson.teacher_review.status == "confirmed" else "pending",
        metadata={
            "audiences": audiences or ["teacher", "student", "parent"],
            "teacher_status": state.lesson.final_reports.teacher.status,
            "student_status": state.lesson.final_reports.student.status,
            "parent_status": state.lesson.final_reports.parent.status,
        },
    )
    return state
